### ISSUE TITLE
Why ... for every default function?

### ISSUE THREAD

**Issue by const-ae** [Bioconductor/MatrixGenerics#10]
If see it correctly, in https://github.com/Bioconductor/MatrixGenerics/pull/8/commits/81aa9cd4b298f489fe2557107f988e6ea5972f27 you added `...` back to every function, right?

If matrixStats explicitly states in the documentation that the `...` are not used within a function, I am not sure  what is the advantage of having it in the method signature?

**Comment by PeteHaitch** [comment]
It seemed better that `foo,matrix-method` defined in **MatrixGenerics** exactly matched `matrixStats::foo()` but I could be persuaded otherwise.
I kept them there in case Henrik starts using `...` in `matrixStats::foo()`.
FWIW there are some `matrixStats::foo()` that do use `...`, e.g., `matrixStats::colQuantiles()`.

**Comment by const-ae** [comment]
> It seemed better that foo,matrix-method defined in MatrixGenerics exactly matched matrixStats::foo() but I could be persuaded otherwise.

Oh, I see you also added some tests that test if the signatures are equal. That is a good idea.

> I kept them there in case Henrik starts using ... in matrixStats::foo().

Yeah, okay. I guess that makes sense. I will close this issue then :)
