### ISSUE TITLE
matrixStats: Next release will break MatrixGenerics 1.2.0 package tests

### ISSUE THREAD

**Issue by HenrikBengtsson** [Bioconductor/MatrixGenerics#22]
Hi, I'm submitting the next release of matrixStats to CRAN.  Reverse-package dependency checks show that out of 313 packages, MatrixGenerics package is the only package where its package tests fail (see below).  These package tests are related to the tidying up and robustification of the `center` argument.

Since MatrixGenerics 1.2.0 is part of Bioconductor _release_, it needs to be "bug fixed" there.  The version to test against is:

```r
remotes::install_github("HenrikBengtsson/matrixStats", ref = "develop")
```

How quickly would you be able to roll out a fix there?  The sooner the better for me as it spares me having to rerun all the revdep checks.

From https://github.com/HenrikBengtsson/matrixStats/blob/develop/revdep/problems.md#matrixgenerics:

```r
...
   4.     └─matrixStats::rowSds(...)
   5.       └─matrixStats::rowVars(...)
  ── Error (test-api_compatibility.R:1445:2): rowVars works  ─────────────────────
  Error: Argument 'center' should be of the same length as number of rows of 'x': 16 != 12
  Backtrace:
      █
   1. ├─MatrixGenerics::rowVars(...) test-api_compatibility.R:1445:8
   2. └─MatrixGenerics::rowVars(...)
   3.   └─MatrixGenerics:::.local(x, rows, cols, na.rm, center, ...)
   4.     └─matrixStats::rowVars(...)
  ── Error (test-api_compatibility.R:1466:2): rowWeightedMads works  ─────────────
  Error: Argument 'center' should be of the same length as number of rows of 'x': 1 != 6
  Backtrace:
      █
   1. ├─MatrixGenerics::rowWeightedMads(...) test-api_compatibility.R:1466:8
   2. └─MatrixGenerics::rowWeightedMads(...)
   3.   └─matrixStats::rowWeightedMads(...)
  
  [ FAIL 10 | WARN 0 | SKIP 0 | PASS 300 ]
  Error: Test failures
  Execution halted
```

**Comment by PeteHaitch** [comment]
Thanks, Henrik. I can take a look over the weekend (it's already Friday morning here)

**Comment by const-ae** [comment]
I already fixed some stuff in https://github.com/Bioconductor/MatrixGenerics/tree/develop

I am in a meeting right now, but also can take a look in the coming days :)

**Comment by PeteHaitch** [comment]
ah i hadn't seen that. Can I leave you to merge those changes in first, @const-ae ?

**Comment by const-ae** [comment]
Sure, but I will probably be only able to do this tomorrow afternoon (it's still Thursday evening here).

**Comment by const-ae** [comment]
Okay, this wasn't as bad as I was afraid it might be. https://github.com/Bioconductor/MatrixGenerics/commit/4b1b995b05359676459ef6739889d8ad59a0ffd0 should make MatrixGenerics compatible with the upcoming matrixStats release. At least on my computer all tests succeed with the new matrixStats version. But please check again that I didn't mess anything up, I had a few issues getting the git commit history in line...

In the future, I'd suggest we use the `develop` branch to track changes in the `matrixStats@develop` branch, so that we can easily switch when the next release comes along. 

And in terms of making the changes available: do I understand this correctly, that we will need to push a bug fix update to the `RELEASE_3_12` branch so that it stays compatible. Should we then also require the `0.57.0-9001` version of matrixStats in the DESCRIPTION file? And I guess, we will also need to bug fix DelayedMatrixStats and sparseMatrixStats, right?

**Comment by PeteHaitch** [comment]
Thanks! It passes `R CMD check` (just an existing `WARNING`) on my system (macOS). 

> In the future, I'd suggest we use the develop branch to track changes in the matrixStats@develop branch, so that we can easily switch when the next release comes along.

I'm not sure that's necessary because we have `release` and `devel` branches in BioC, with (github) `master` basically tracking the `devel` BioC branch. But perhaps I've misunderstood.

> And in terms of making the changes available: do I understand this correctly, that we will need to push a bug fix update to the RELEASE_3_12 branch so that it stays compatible. Should we then also require the 0.57.0-9001 version of matrixStats in the DESCRIPTION file? 

I think we'll need to push this fix to the `devel` branch and patch the `release` branch (hopefully using `git cherry-pick`) once the new version of **matrixStats** is available. And, yes, we'll need to increase the minimum **matrixStats** version in the `DESCRIPTION` on both branches. I suggest we use the version number of whatever gets released to CRAN by @HenrikBengtsson  rather than his current devel version number.

> And I guess, we will also need to bug fix DelayedMatrixStats and sparseMatrixStats, right?

Yes, I think we'll need to check **DMS** and **SMS** work with these changes to **MatrixGenerics**.

**Comment by HenrikBengtsson** [comment]
Thanks for this.

> But please check again that I didn't mess anything up, I had a few issues getting the git commit history in line...

I've verified that it's now fixed using:

```sh
$ git clone git@github.com:Bioconductor/MatrixGenerics.git
$ (cd MatrixGenerics; git log -1)
commit 4b1b995b05359676459ef6739889d8ad59a0ffd0 (HEAD -> master, origin/master, origin/HEAD)
Author: const-ae <artjom31415@googlemail.com>
Date:   Thu Jan 21 23:27:53 2021 +0100

    Make MatrixGenerics compatible with upcoming matrixStats release
    
    * This commit reverts d1670c715, 4080842, and b353297 and resets the
    state to the one from the develop branch

$ R CMD build MatrixGenerics
$ R CMD --as-cran MatrixGenerics_1.3.0.tar.gz
```

I tested against the upcoming matrixStats 0.57.0-9001 (to become 0.58.0).

However, when testing against matrixStats 0.57.0, I get:

```sh
* checking examples ... ERROR
Running examples in ‘MatrixGenerics-Ex.R’ failed
The error most likely occurred in:

> base::assign(".ptime", proc.time(), pos = "CheckExEnv")
> ### Name: rowAvgsPerColSet
> ### Title: Calculates for each row (column) a summary statistic for equally
> ###   sized subsets of columns (rows)
> ### Aliases: rowAvgsPerColSet
> ###   rowAvgsPerColSet,matrix_OR_array_OR_table_OR_numeric-method
> ###   rowAvgsPerColSet,ANY-method colAvgsPerRowSet
> ###   colAvgsPerRowSet,matrix_OR_array_OR_table_OR_numeric-method
> ###   colAvgsPerRowSet,ANY-method
> ### Keywords: array iteration robust univar2
> 
> ### ** Examples
> 
>   mat <- matrix(rnorm(20), nrow = 5, ncol = 4)
>   mat[2, 1] <- NA
>   mat[3, 3] <- Inf
>   mat[4, 1] <- 0
>   
>   print(mat)
           [,1]       [,2]       [,3]        [,4]
[1,] -0.6264538 -0.8204684  1.5117812 -0.04493361
[2,]         NA  0.4874291  0.3898432 -0.01619026
[3,] -0.8356286  0.7383247        Inf  0.94383621
[4,]  0.0000000  0.5757814 -2.2146999  0.82122120
[5,]  0.3295078 -0.3053884  1.1249309  0.59390132
>   
>   S <- matrix(1:ncol(mat), ncol = 2)
>   print(S)
     [,1] [,2]
[1,]    1    3
[2,]    2    4
>   
>   rowAvgsPerColSet(mat, S = S, FUN = rowMeans)
Error in FUN(Zjj, ..., na.rm = na.rm) : 
  formal argument "na.rm" matched by multiple actual arguments
Calls: rowAvgsPerColSet -> rowAvgsPerColSet -> <Anonymous> -> apply -> FUN
Execution halted
* checking for unstated dependencies in ‘tests’ ... OK
* checking tests ...
  Running ‘testthat.R’
 ERROR
Running the tests in ‘tests/testthat.R’ failed.
Last 13 lines of output:
   2. └─MatrixGenerics::rowAvgsPerColSet(X = mat, S = S, FUN = rowMeans)
   3.   └─matrixStats::rowAvgsPerColSet(...)
   4.     └─base::apply(...)
   5.       └─matrixStats:::FUN(newX[, i], ...)
  ── Error (test-api_compatibility.R:1462:2): rowWeightedMads works  ─────────────
  Error: Argument 'center' must be a scalar or NULL
  Backtrace:
      █
   1. ├─MatrixGenerics::rowWeightedMads(...) test-api_compatibility.R:1462:8
   2. └─MatrixGenerics::rowWeightedMads(...)
   3.   └─matrixStats::rowWeightedMads(...)
  
  [ FAIL 6 | WARN 0 | SKIP 0 | PASS 296 ]
  Error: Test failures
  Execution halted
```

Right now, I'm not sure if that's on me or on you.

My other concern is that MatrixGenerics 1.3.0 is the Bioc devel version - is that a mistake?

> Should we then also require the 0.57.0-9001 version of matrixStats in the DESCRIPTION file?

I don't think that is "valid" version to depend on by R standards, at least not by `--as-cran`, so better not to spread that.  The next release of matrixStats will be 0.58.0.  

However, I think the new MatrixGenerics  1.2.1 should be written such that it's also compatible with matrixStats 0.57.0.  Then you can keep it as is.

**Comment by HenrikBengtsson** [comment]
Oh...

```
Error: Argument 'center' must be a scalar or NULL
```

seems like a potentially complicated update for you.  You'd have to do something like:

```r
center <- rep(6, times = nrow(X))
if (packageVersion("matrixStats") <= "0.57.0") center <- center[1]
rowWeightedMads(X, center = center)
```

to make this compatible with matrixStats 0.57.0 as well.

**Comment by HenrikBengtsson** [comment]
> patch the release branch (hopefully using git cherry-pick ) once the new version of matrixStats is available.

Oh, are you waiting for me? ... because I was actually waiting for you to patch before so my update doesn't break your package.

**Comment by PeteHaitch** [comment]
Sorry for the delay, Henrik. I received some sad personal news over the weekend but I'll try to address this today or tomorrow.

**Comment by HenrikBengtsson** [comment]
I'm sorry to hear. No rush - whatever and whenever you prefer. Take care.

**Comment by PeteHaitch** [comment]
After some fussing about I *thought* I had it sorted, but now that I write this I'm not sure if it's how you wanted it done @HenrikBengtsson ...

Both of the following versions of **MatrixGenerics** pass `R CMD check` for me with **matrixStats** `v0.57.0.9001` (https://github.com/HenrikBengtsson/matrixStats/commit/60551ca1a168d1f54f48abcd2132f8b6c986204e)
- f66204eb36ec33018b94f715226d621553eed5a1 will be `v1.3.1` on BioC devel (BioC 3.13)
- abcc9ca0504e0b915cd7933a3169a8e9e5bd2fe9 will be `v1.2.1` on BioC release (BioC 3.12)

Right now, these versions of **MatrixGenerics** are GitHub-only (i.e. they haven't yet been pushed to BioC git server). That's because these can only pass BioC's checks once **matrixStats** `v0.58.0` is available from CRAN. But now I'm worried I'd made a block for you to get this next version of **matrixStats** onto CRAN, @HenrikBengtsson ...

Sorry if I've overcomplicated things, it's been a long week

**Comment by HenrikBengtsson** [comment]
AFAIK, CRAN doesn't care about broken revdep packages on Bioconductor, so in that sense it's not a blocker.

I can submit to CRAN if it's ok with Bioc that it'll break MatrixGenerics tests.  (It's not break the functionality so no one should be affected). Is that OK?

The alternative is to patch the package tests of MatrixGenerics so they run conditionally on matrixStats version.

**Comment by PeteHaitch** [comment]
I'm fine with a temporary breaking of tests and prefer that to implementing conditional testing

**Comment by HenrikBengtsson** [comment]
Righty-oh.  I'll go ahead and prepare for my CRAN submission.

**Comment by HenrikBengtsson** [comment]
[matrixStats 0.58.0](https://cran.r-project.org/web/packages/matrixStats/index.html) is now on CRAN;

> From: Uwe Ligges
> Date: Fri, Jan 29, 2021 at 3:49 PM PST
> Subject: Re: [CRAN-pretest-waiting] CRAN submission matrixStats 0.58.0
> To: Henrik Bengtsson, CRAN-submissions
> 
> Thanks, on its way to CRAN.

**Comment by PeteHaitch** [comment]
I'll push to bioc later today. Thanks Henrik!

**Comment by PeteHaitch** [comment]
And done. I'll keep an eye out for the next build report to make sure there's no surprises.
